/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.awt.Color;

/**
 *
 * @author DiegoAlvarez
 */
public class Simbolo extends javax.swing.JPanel {

    /**
     * Creates new form ResultsPanel
     */
    public Simbolo() {
        initComponents();
    }

    public Simbolo(String Id, String clase, String params, String type, String value) {
        initComponents();
        this.type.setText(type);
        this.value.setText(value);
        this.Id.setText(Id);
        this.clase.setText(clase);
        this.params.setText(params);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        clase = new javax.swing.JLabel();
        Id = new javax.swing.JLabel();
        type = new javax.swing.JLabel();
        value = new javax.swing.JLabel();
        params = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createEmptyBorder(2, 2, 2, 2));

        clase.setFont(new java.awt.Font("Segoe UI Historic", 1, 12)); // NOI18N
        clase.setText("CLASE");

        Id.setFont(new java.awt.Font("Segoe UI Historic", 1, 12)); // NOI18N
        Id.setText("IDENTIFICADOR");

        type.setFont(new java.awt.Font("Segoe UI Historic", 1, 12)); // NOI18N
        type.setText("TIPO");

        value.setFont(new java.awt.Font("Segoe UI Historic", 1, 12)); // NOI18N
        value.setText("VALOR");
        value.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        params.setFont(new java.awt.Font("Segoe UI Historic", 1, 12)); // NOI18N
        params.setText("PARAMETROS");
        params.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(clase, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Id, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(type)
                .addGap(18, 18, 18)
                .addComponent(value)
                .addGap(18, 18, 18)
                .addComponent(params, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(clase)
                .addComponent(Id)
                .addComponent(type, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(value, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(params, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel Id;
    public javax.swing.JLabel clase;
    public javax.swing.JLabel params;
    public javax.swing.JLabel type;
    public javax.swing.JLabel value;
    // End of variables declaration//GEN-END:variables
}
