
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sat Oct 29 16:09:38 CST 2022
//----------------------------------------------------

package Sintactico;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Extern = 14;
  public static final int OperadorDivAsignacion = 59;
  public static final int OperadorModulo = 47;
  public static final int Return = 22;
  public static final int OperadorResta = 44;
  public static final int OperadorDesplIzAsig = 68;
  public static final int Hilera = 72;
  public static final int OperadorModuloAsignacion = 64;
  public static final int Break = 4;
  public static final int OperadorDoblePunto = 54;
  public static final int Long = 20;
  public static final int Default = 9;
  public static final int Char = 6;
  public static final int OperadorParentesisDer = 49;
  public static final int OperadorORAsignacion = 67;
  public static final int For = 16;
  public static final int Void = 32;
  public static final int Else = 12;
  public static final int Int = 19;
  public static final int OperadorCorcheteIz = 52;
  public static final int OperadorPuntoComa = 35;
  public static final int OperadorBooleano = 40;
  public static final int OperadorComa = 36;
  public static final int Typedef = 29;
  public static final int OperadorMultAsignacion = 58;
  public static final int OperadorDesplDer = 61;
  public static final int Main = 2;
  public static final int Caracter = 73;
  public static final int OperadorComplementoAUno = 63;
  public static final int Do = 10;
  public static final int Static = 26;
  public static final int OperadorMultiplicacion = 45;
  public static final int Signed = 24;
  public static final int Unsigned = 31;
  public static final int Short = 23;
  public static final int OperadorSuma = 43;
  public static final int Case = 5;
  public static final int OperadorDesIz = 62;
  public static final int Volatile = 33;
  public static final int Const = 7;
  public static final int Continue = 8;
  public static final int OperadorMiembroPuntero = 70;
  public static final int OperadorCorcheteDer = 53;
  public static final int OperadorGato = 71;
  public static final int Sizeof = 25;
  public static final int OperadorRestaAsignacion = 57;
  public static final int OctalFlotante = 79;
  public static final int Auto = 3;
  public static final int If = 18;
  public static final int FlotanteExponente = 77;
  public static final int Flotante = 76;
  public static final int EOF = 0;
  public static final int OperadorANDAsignacion = 65;
  public static final int Hexadecimal = 80;
  public static final int Double = 11;
  public static final int Struct = 27;
  public static final int HexadecimalFlotante = 81;
  public static final int OperadorIncremento = 37;
  public static final int OperadorIgual = 42;
  public static final int Octal = 78;
  public static final int error = 1;
  public static final int OperadorParentesisIz = 48;
  public static final int OperadorIgualIgual = 39;
  public static final int Error = 82;
  public static final int Enum = 13;
  public static final int Float = 15;
  public static final int OperadorPregunta = 41;
  public static final int OperadorDesplDerAsig = 69;
  public static final int Identificador = 74;
  public static final int OperadorDireccion = 60;
  public static final int OperadorDecremento = 38;
  public static final int Entero = 75;
  public static final int OperadorParCuadradoDer = 51;
  public static final int OperadorDivision = 46;
  public static final int OperadorPunto = 55;
  public static final int OperadorParCuadradoIz = 50;
  public static final int Register = 21;
  public static final int OperadorXORAsignacion = 66;
  public static final int OperadorSumaAsignacion = 56;
  public static final int Goto = 17;
  public static final int While = 34;
  public static final int Union = 30;
  public static final int Switch = 28;
}

