
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Oct 24 03:00:53 CST 2022
//----------------------------------------------------

package Sintactico;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Extern = 13;
  public static final int OperadorDivAsignacion = 58;
  public static final int OperadorModulo = 46;
  public static final int Return = 21;
  public static final int OperadorResta = 43;
  public static final int OperadorDesplIzAsig = 67;
  public static final int Hilera = 71;
  public static final int OperadorModuloAsignacion = 63;
  public static final int Break = 3;
  public static final int OperadorDoblePunto = 53;
  public static final int Long = 19;
  public static final int Default = 8;
  public static final int Char = 5;
  public static final int OperadorParentesisDer = 48;
  public static final int OperadorORAsignacion = 66;
  public static final int For = 15;
  public static final int Void = 31;
  public static final int Else = 11;
  public static final int Int = 18;
  public static final int OperadorCorcheteIz = 51;
  public static final int OperadorPuntoComa = 34;
  public static final int OperadorBooleano = 39;
  public static final int OperadorComa = 35;
  public static final int Typedef = 28;
  public static final int OperadorMultAsignacion = 57;
  public static final int OperadorDesplDer = 60;
  public static final int Caracter = 72;
  public static final int OperadorComplementoAUno = 62;
  public static final int Do = 9;
  public static final int Static = 25;
  public static final int OperadorMultiplicacion = 44;
  public static final int Signed = 23;
  public static final int Unsigned = 30;
  public static final int Short = 22;
  public static final int OperadorSuma = 42;
  public static final int Case = 4;
  public static final int OperadorDesIz = 61;
  public static final int Volatile = 32;
  public static final int Const = 6;
  public static final int Continue = 7;
  public static final int OperadorMiembroPuntero = 69;
  public static final int OperadorCorcheteDer = 52;
  public static final int OperadorGato = 70;
  public static final int Sizeof = 24;
  public static final int OperadorRestaAsignacion = 56;
  public static final int OctalFlotante = 78;
  public static final int Auto = 2;
  public static final int If = 17;
  public static final int FlotanteExponente = 76;
  public static final int Flotante = 75;
  public static final int EOF = 0;
  public static final int OperadorANDAsignacion = 64;
  public static final int Hexadecimal = 79;
  public static final int Double = 10;
  public static final int Struct = 26;
  public static final int HexadecimalFlotante = 80;
  public static final int OperadorIncremento = 36;
  public static final int OperadorIgual = 41;
  public static final int Octal = 77;
  public static final int Error = 1;
  public static final int OperadorParentesisIz = 47;
  public static final int OperadorIgualIgual = 38;
  public static final int Enum = 12;
  public static final int Float = 14;
  public static final int OperadorPregunta = 40;
  public static final int OperadorDesplDerAsig = 68;
  public static final int Identificador = 73;
  public static final int OperadorDireccion = 59;
  public static final int OperadorDecremento = 37;
  public static final int Entero = 74;
  public static final int OperadorParCuadradoDer = 50;
  public static final int OperadorDivision = 45;
  public static final int OperadorPunto = 54;
  public static final int OperadorParCuadradoIz = 49;
  public static final int Register = 20;
  public static final int OperadorXORAsignacion = 65;
  public static final int OperadorSumaAsignacion = 55;
  public static final int Goto = 16;
  public static final int While = 33;
  public static final int Union = 29;
  public static final int Switch = 27;
}

