
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Nov 28 23:06:00 CST 2022
//----------------------------------------------------

package Sintactico;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int OperadorComa = 3;
  public static final int Entero = 17;
  public static final int OperadorMayor = 40;
  public static final int Hexadecimal = 22;
  public static final int If = 31;
  public static final int OperadorMasIgual = 59;
  public static final int Void = 33;
  public static final int OperadorXOR = 46;
  public static final int Default = 35;
  public static final int OperadorMas = 54;
  public static final int Else = 32;
  public static final int OperadorIgualIgual = 61;
  public static final int OperadorANDLazy = 45;
  public static final int Break = 37;
  public static final int Read = 27;
  public static final int OperadorORLazy = 44;
  public static final int OperadorAND = 48;
  public static final int Error = 62;
  public static final int OperadorMenosIgual = 60;
  public static final int OperadorCorcheteIz = 5;
  public static final int Long = 15;
  public static final int While = 29;
  public static final int FlotanteExponente = 19;
  public static final int OperadorModIgual = 51;
  public static final int Int = 14;
  public static final int Flotante = 18;
  public static final int For = 28;
  public static final int EOF = 0;
  public static final int OperadorModulo = 58;
  public static final int error = 1;
  public static final int Switch = 30;
  public static final int OperadorNegacion = 6;
  public static final int HexadecimalFlotante = 23;
  public static final int OperadorParentesisIz = 9;
  public static final int Char = 13;
  public static final int Continue = 36;
  public static final int Case = 34;
  public static final int OperadorDesigual = 43;
  public static final int Short = 16;
  public static final int OperadorOR = 47;
  public static final int OperadorIgual = 38;
  public static final int Const = 25;
  public static final int Octal = 20;
  public static final int Identificador = 2;
  public static final int OperadorMenorIgual = 41;
  public static final int Caracter = 24;
  public static final int OperadorMultiIgual = 49;
  public static final int OperadorDecremental = 53;
  public static final int OperadorPuntoComa = 12;
  public static final int Write = 26;
  public static final int OperadorMultiplicacion = 56;
  public static final int OperadorParentesisDer = 8;
  public static final int OperadorIncremental = 52;
  public static final int OperadorParCuadradoIz = 10;
  public static final int OperadorDivision = 57;
  public static final int OperadorDoblePunto = 7;
  public static final int OperadorMenos = 55;
  public static final int OperadorMayorIgual = 39;
  public static final int OperadorMenor = 42;
  public static final int OperadorDivIgual = 50;
  public static final int OctalFlotante = 21;
  public static final int OperadorParCuadradoDer = 11;
  public static final int OperadorCorcheteDer = 4;
}

